### ISSUE TITLE
JSTL tags

### ISSUE THREAD

**Issue by ghost** [fourcube/undertow-jsp-sample#1]
@cgrieger @fourcube 

Can you use JSTL tags in the JSPs compiled by this? I wasn't able to.

**Comment by fourcube** [comment]
I've updated the code to support JSTL. Does it work for you now?

**Comment by ghost** [comment]
Wow! I was just working on developing similar code for preparing the TagLibraryInfo data manually from the tld files. Thanks a lot. I will look into what you have done.

**Comment by ghost** [comment]
Looks good! I haven't ran it with my code yet though. One thing I noticed is that all the jars in the classpath are scanned with the TldLocator. I may modify it to give the option to scan everything or only a list of jars.

**Comment by fourcube** [comment]
Credit goes to @djotanov (https://github.com/djotanov/undertow-jsp-template), I took the code from there.

Glad everything works fine, I'll close this issue then.

**Comment by ghost** [comment]
Thank you so much!  

One thing though: Can you still grab the following dependencies from Maven? 

org.jboss.metadata:jboss-metadata-common:8.0.0.Final
org.jboss.metadata:jboss-metadata-web:8.0.0.Final

I couldn't grab them with Ivy.

**Comment by ghost** [comment]
Oh, I see, you got it from the jboss repo. I will try that.

**Comment by ghost** [comment]
Got it and the code worked. Thanks a million.
